version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:5173
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 5000:5000
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379
    restart: unless-stopped
    volumes:
      - redis_server:/data

  db:
    image: postgres:16-alpine
    container_name: postgresql
    ports:
      - 5432
    restart: unless-stopped
    volumes:
      - postgresql_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

volumes:
  redis_server:
  postgresql_database:
